[package]
name = "rpi-server"
description = "Rasbperry Pi web server"
version = "1.0.0"
edition = "2021"
license = "MIT"

[profile.release]
# Reduce parallel code generation units to increase optimization.
codegen-units = 1
# Link time optimization.
lto = true
strip = true

[dependencies]
actix-files = "0.6.6"
actix-web = "4.7.0"
actix-web-httpauth = "0.8.1"
anyhow = "1.0.86"
async-stream = "0.3.5"
bluez-async = "0.7.2"
env_logger = "0.11.3"
futures = "0.3.30"
log = "0.4.21"
# Using tokio process instead of std to avoid zombie processes
# when calling commands from Actix Web endpoints.
tokio = { version = "1.38.0", features = ["process"] }
